---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - backup.sts-backup.io
  resources:
  - statefulsetbackups
  - statefulsetrestores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - backup.sts-backup.io
  resources:
  - statefulsetbackups/finalizers
  - statefulsetrestores/finalizers
  verbs:
  - update
- apiGroups:
  - backup.sts-backup.io
  resources:
  - statefulsetbackups/status
  - statefulsetrestores/status
  verbs:
  - get
  - patch
  - update
