# This rule is not used by the project statefulset-backup-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to backup.sts-backup.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: statefulset-backup-operator
    app.kubernetes.io/managed-by: kustomize
  name: statefulsetbackup-viewer-role
rules:
- apiGroups:
  - backup.sts-backup.io
  resources:
  - statefulsetbackups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - backup.sts-backup.io
  resources:
  - statefulsetbackups/status
  verbs:
  - get
