apiVersion: backup.sts-backup.io/v1alpha1
kind: StatefulSetRestore
metadata:
  labels:
    app.kubernetes.io/name: statefulset-backup-operator
    app.kubernetes.io/managed-by: kustomize
  name: statefulsetrestore-sample
spec:
  # TODO(user): Add fields here
